import Head from "next/head";
import { InferGetServerSidePropsType } from "next";
import { initializeEnvironment } from "./helpers/runtime-env";
import { MyComponent } from "./components/MyComponent";
import { RuntimeScript } from "./helpers/RuntimeEnv";

export async function getServerSideProps() {
	await initializeEnvironment("test");

	return {
		props: {},
	};
}

function Home(props: InferGetServerSidePropsType<typeof getServerSideProps>) {
	return (
		<div>
			<Head>
				<title>Next 12 runtime environment</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<RuntimeScript />
			</Head>
			<div>
				<MyComponent />
			</div>
		</div>
	);
}

export default Home;
