import Head from "next/head";
import { MyComponent } from "@acme/my-component";
import { GetServerSidePropsContext } from "next";
import { contextify } from "../server/contextify";
import { ChangeEnvironment } from "../components/change-environment";
import { getNetlifyEnv } from "../helpers/get-netlify-env";
import { isNetlifyDeployPreview } from "../helpers/is-netlify-deploy-preview";
import { NotAllowed } from "../components/not-allowed";

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
	const env = await getNetlifyEnv(ctx);

	contextify.initialize(env);

	return {
		props: {},
	};
}

function Home() {
	return (
		<div>
			<Head>
				<title>Next 12 runtime environment</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<div className="container mx-auto space-y-4 py-4">
					<h1 className="text-2xl font-bold">Next 12 runtime environment</h1>
					<MyComponent />
					{isNetlifyDeployPreview() ? <ChangeEnvironment /> : <NotAllowed />}
				</div>
			</div>
		</div>
	);
}

export default Home;
