import Head from "next/head";
import { EnvironmentCard, Show } from "@acme/shared";
import { GetServerSidePropsContext } from "next";
import { contextify } from "../server/contextify";
import { ChangeEnvironmentCard } from "../components/change-environment-card";
import { getNetlifyEnv } from "../helpers/get-netlify-env";
import { isNetlifyDeployPreview } from "../helpers/is-netlify-deploy-preview";
import { NotAllowedCard } from "../components/not-allowed-card";

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
	const context = await getNetlifyEnv(ctx);

	contextify.switchContext(context);

	return {
		props: {},
	};
}

export default function Home() {
	return (
		<div>
			<Head>
				<title>Next 12 runtime environment</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<div className="container mx-auto space-y-4 py-4">
					<h1 className="text-2xl font-bold">Next 12 runtime environment</h1>
					<div className="grid grid-cols-1 gap-4 md:grid-cols-2">
						<EnvironmentCard />
						<Show when={isNetlifyDeployPreview()} fallback={<NotAllowedCard />}>
							<ChangeEnvironmentCard />
						</Show>
					</div>
				</div>
			</div>
		</div>
	);
}
